apiVersion: v1
kind: PersistentVolume
metadata:
  name: s3-pv
spec:
  capacity:
    storage: 1200Gi # Ignored, required
  accessModes:
    - ReadWriteMany # Supported options: ReadWriteMany / ReadOnlyMany
  storageClassName: "" # Required for static provisioning
  claimRef: # To ensure no other PVCs can claim this PV
    namespace: default # Namespace is required even though it's in "default" namespace.
    name: s3-pvc # Name of your PVC
  mountOptions:
    - allow-delete
    - region eu-west-1
  csi:
    driver: s3.csi.aws.com # Required
    volumeHandle: s3-csi-driver-volume # Must be unique
    volumeAttributes:
      bucketName: s3-csi-driver
      # authenticationSource: pod
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: s3-pvc
spec:
  accessModes:
    - ReadWriteMany # Supported options: ReadWriteMany / ReadOnlyMany
  storageClassName: "" # Required for static provisioning
  resources:
    requests:
      storage: 1200Gi # Ignored, required
  volumeName: s3-pv # Name of your PV
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: s3-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: s3-app
  template:
    metadata:
      labels:
        app: s3-app
      annotations:
        s3.csi.aws.com/sidecar: "true"
    spec:
      serviceAccountName: s3-workload-sa
      # schedulingGates:
      #   - name: s3.csi.aws.com/reserve-headroom-for-mppod
      # nodeSelector:
      #   karpenter.sh/nodepool: default
        # role: workloads
        # kubernetes.io/hostname: "ip-10-0-1-101.ec2.internal"
      containers:
        - name: app
          image: ubuntu
          command: ["/bin/sh"]
          args: ["-c", "while true; do echo \"$(date -u): Contents of file.txt:\"; echo \"===================\"; cat /data/file.txt; echo \"===================\"; echo; sleep 1; done"]
          volumeMounts:
            - name: persistent-storage
              mountPath: /data
              mountPropagation: HostToContainer
      volumes:
        - name: persistent-storage
          persistentVolumeClaim:
            claimName: s3-pvc
